FROM node:22-alpine


COPY app /app/
COPY components /components/
COPY lib /lib/
COPY public /public/
COPY .clerk /.clerk/
COPY eslint.config.mjs ./
COPY middleware.ts ./
COPY next.config.ts ./
COPY package-lock.json ./
COPY package.json ./
COPY postcss.config.mjs ./
COPY stack.tsx ./
COPY .env.local ./
COPY next-env.d.ts ./
COPY next.config.ts ./

WORKDIR /app

RUN npm install

EXPOSE 3003

COPY . .

CMD ["npm", "run", "dev"]