#https://medium.com/@itsuki.enjoy/dockerize-a-next-js-app-4b03021e084d

FROM node:22.15.1-alpine3.20


COPY app /app/
COPY components /components/
COPY lib /lib/
COPY public /public/
COPY .clerk /.clerk/
#COPY .next /.next/
COPY eslint.config.mjs ./
COPY middleware.ts ./
COPY next.config.ts ./
COPY package-lock.json ./
COPY package.json ./
COPY postcss.config.mjs ./
COPY stack.tsx ./
COPY .env.local ./
COPY next-env.d.ts ./
COPY next.config.ts ./

WORKDIR /app

RUN npm install
#RUN npm run build
# RUN npm run dev

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

EXPOSE 3002

# CMD ["npm", "start"]
CMD npm run dev